// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9pn9yT6i_A_3a3HuDKC7HtZIzCARcwBo',
    appId: '1:779984113387:web:73a27f6faa5bb3199338ae',
    messagingSenderId: '779984113387',
    projectId: 'surgeryrecoverytracker',
    authDomain: 'surgeryrecoverytracker.firebaseapp.com',
    storageBucket: 'surgeryrecoverytracker.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNEppV2KJl6Nt_ANQfQuQbVizNoQaB25Q',
    appId: '1:779984113387:android:a306818e9ecff55b9338ae',
    messagingSenderId: '779984113387',
    projectId: 'surgeryrecoverytracker',
    storageBucket: 'surgeryrecoverytracker.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzYXDmmnRHAT3ITY_u8PDAEWLTAMRYWoQ',
    appId: '1:779984113387:ios:d0ed11b1c28a877d9338ae',
    messagingSenderId: '779984113387',
    projectId: 'surgeryrecoverytracker',
    storageBucket: 'surgeryrecoverytracker.appspot.com',
    iosBundleId: 'com.example.surgeryRecoveryTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzYXDmmnRHAT3ITY_u8PDAEWLTAMRYWoQ',
    appId: '1:779984113387:ios:d0ed11b1c28a877d9338ae',
    messagingSenderId: '779984113387',
    projectId: 'surgeryrecoverytracker',
    storageBucket: 'surgeryrecoverytracker.appspot.com',
    iosBundleId: 'com.example.surgeryRecoveryTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9pn9yT6i_A_3a3HuDKC7HtZIzCARcwBo',
    appId: '1:779984113387:web:9b40ccf32135be169338ae',
    messagingSenderId: '779984113387',
    projectId: 'surgeryrecoverytracker',
    authDomain: 'surgeryrecoverytracker.firebaseapp.com',
    storageBucket: 'surgeryrecoverytracker.appspot.com',
  );
}
